# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it is preferred to disable the lint only for single test
  # files or single lines of code. Otherwise, disable the lint by commenting
  # it out, and document why with a comment above.
  #
  # "include: package:flutter_lints/flutter.yaml" above imports all rules
  # from this package into the linter as well as all lints
  # from ./analysis_options.yaml files in subdirectories of lib.

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
