name: quran_learning_app
description: Open Source Quran Learning App for Foreigners - Learn Quranic letters, words, translations, and more!
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path: ^1.8.3
  audioplayers: ^5.0.0
  google_fonts: ^6.1.0
  provider: ^6.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
